// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "lCEr01CYeLdJRSmO2iPqe5nXFJcY9E30aXsQHeJUeORm0JiSbZmxxSlpVW7wL7Dg9dNrMp";
}
}
}

